Make UserMenu match DSM
pxblue/react-native-component-library pull request #123
Opened 2021-03-01 21:17 UTC by daileytj

Fixes PXBLUE-1899.

#### Changes proposed in this Pull Request:
- Update InfoListItem typography variants to match DSM
- Make UserMenu match DSM

2021-03-02 12:31 UTC, joebochill reviewed
What about the font colors for the icons and the text, are those matching the DSM?

2021-03-02 12:35 UTC, daileytj commented
> What about the font colors for the icons and the text, are those matching the DSM?

Good catch! I was so focused on typography stuff that I didn't even question the colors. I'll update those to match.

2021-03-02 12:58 UTC, daileytj commented
![Simulator Screen Shot - iPhone 11 - 2021-03-02 at 07 56 39](https://user-images.githubusercontent.com/13989985/109651827-01455d80-7b2d-11eb-9ef7-077cfb4052dd.png)

2021-03-02 18:51 UTC, joebochill commented on components/src/core/user-menu/user-menu.tsx
> +                            styles={{ title: { fontSize: 16, fontWeight: '400' } }}
I believe specifying the numerical fontWeight doesn't work as expected on one of the OSs. Safer way to do this is to pull the font family/weight from the theme (https://github.com/pxblue/react-native-component-library/blob/dev/components/src/core/list-item-tag/list-item-tag.tsx#L44):
```suggestion
                            styles={{ title: { 
                                fontSize: 16, 
                                fontFamily: theme.fonts.regular.fontFamily,
                                fontWeight: theme.fonts.regular.fontFamily
                            }}}
```

2021-03-03 12:40 UTC, joebochill commented
Changes look good, I'm just trying to verify the colors in your screenshot. The icon is gray[500] and the text is black[500] right?

2021-03-03 13:00 UTC, joebochill requested changes

2021-03-03 13:00 UTC, joebochill commented on components/src/core/user-menu/user-menu.tsx
> +                            }}
Colors look good, but adding this styles prop breaks the end-user style overrides functionality. You need to merge these style with any overrides that are being passed in through the menuItem, e.g.:

```
                {menuItems &&
                    menuItems.map((menuItem: InfoListItemProps, index: number) => {
                        const menuStyles = menuItem.styles || {};
                        return (
                            <InfoListItem
                                {...menuItem}
                                key={index}
                                onPress={(): void => {
                                    closeMenu();
                                    if (menuItem.onPress) menuItem.onPress();
                                }}
                                iconColor={iconColor || menuItem.iconColor}
                                fontColor={fontColor || menuItem.fontColor}
                                backgroundColor={backgroundColor || menuItem.backgroundColor}
                                styles={
                                    Object.assign(menuStyles, {
                                        title: Object.assign({
                                            fontSize: 16,
                                            fontFamily: theme.fonts.regular.fontFamily,
                                            fontWeight: theme.fonts.regular.fontWeight,
                                        }, menuStyles.title)
                                    })
                                }
                            />
                        )
                    })}
```

2021-03-03 13:59 UTC, daileytj commented
> Changes look good, I'm just trying to verify the colors in your screenshot. The icon is gray[500] and the text is black[500] right?

Correct.

2021-03-03 14:00 UTC, joebochill approved these changes

2021-03-03 14:05 UTC, merged